version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - budy-backend_sail
    depends_on:
      - mysql

networks:
  budy-backend_sail:
    external: true